# Generated by Django 3.0.3 on 2020-04-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_userprofileinfomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfomodel',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
